[versions]
androidDesugarJdkLibs = "2.1.5"
kotlin = "2.2.21"
ksp = "2.2.21-2.0.4"
androidGradlePlugin = "8.13.2"
androidTools = "31.13.2"

minSdk = "28"
targetSdk = "36"
compileSdk = "36"
versionName = "1.26"
versionCode = "27"

ktx = "1.17.0"
material = "1.13.0"
appcompat = "1.7.1"
immutableCollection = "0.4.0"
lifecycle = "2.10.0"
coroutines = "1.10.2"

composeBom = "2025.12.00"
composeGradle = "1.9.3"
composeNavigation = "2.9.6"
composeJunit = "1.10.0"
accompanist = "0.36.0"
coil = "3.3.0"
composeActivity = "1.12.1"
fbBom = "34.6.0"

hilt = "2.57.2"
hiltCompose = "1.3.0"

mockk = "1.14.7"
junit = "6.0.1"
androidxJunit = "1.3.0"
espresso = "3.7.0"
robolectric = "4.16"
androidxTest = "1.7.0"
kermit = "2.0.8"
robolectricExt = "0.9.0"
gms = "4.4.4"
fbCrashlytics = "3.0.6"

room = "2.8.4"
vkompose = "0.7.1"
serialization = "1.9.0"
datetime = "0.7.1"
paging = "3.3.6"
slf4j = "2.0.17"
coroutineTest = "1.10.2"
datastore = "1.2.0"
composeCharts = "0.1.11"
detekt = "1.23.8"
detektCompose = "0.5.1"

# decompose dependencies
essenty = "2.5.0"
parcelize = "0.2.4"
junitJupiter = "5.13.4"
junitKtx = "1.3.0"

# Other tools
haze = "1.7.1"
[libraries]
android-desugarJdkLibs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "androidDesugarJdkLibs" }
android-gradlePlugin = { module = "com.android.tools.build:gradle", version.ref = "androidGradlePlugin" }

kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-serialization = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin" }
ksp-gradlePlugin = { group = "com.google.devtools.ksp", name = "com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }
android-tools-common = { group = "com.android.tools", name = "common", version.ref = "androidTools" }
room-gradlePlugin = { group = "androidx.room", name = "room-gradle-plugin", version.ref = "room" }
vkompose-gradlePlugin = { group = "com.vk.vkompose", name = "com.vk.vkompose.gradle.plugin", version.ref = "vkompose" }
composeCompiler-gradlePlugin = { group = "org.jetbrains.compose", name = "compose-gradle-plugin", version.ref = "composeGradle" }
fbCrashlytics-gradlePlugin = { module = "com.google.firebase:firebase-crashlytics-gradle", version.ref = "fbCrashlytics" }

androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "ktx" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
lifecycle-viewModel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
lifecycle-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycle" }
coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }

kotlin-compiler-embeddable = { group = "org.jetbrains.kotlin", name = "kotlin-compiler-embeddable", version.ref = "kotlin" }

androidx-compose-bom = { group = "androidx.compose", name = "compose-bom-alpha", version.ref = "composeBom" }

androidx-compose-activity = { group = "androidx.activity", name = "activity-compose", version.ref = "composeActivity" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-material = { group = "androidx.compose.material", name = "material" }
androidx-compose-material-icons-core = { group = "androidx.compose.material", name = "material-icons-core" }
androidx-compose-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-animation = { group = "androidx.compose.animation", name = "animation" }
androidx-compose-animationGraphics = { group = "androidx.compose.animation", name = "animation-graphics" }
androidx-compose-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }
androidx-compose-runtime = { group = "androidx.compose.runtime", name = "runtime" }

androidx-compose-navigation = { group = "androidx.navigation", name = "navigation-compose", version.ref = "composeNavigation" }

androidx-compose-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4", version.ref = "composeJunit" }

dev-haze-core = { group = "dev.chrisbanes.haze", name = "haze", version.ref = "haze" }
dev-haze-materials = { group = "dev.chrisbanes.haze", name = "haze-materials", version.ref = "haze" }

coil-compose = { group = "io.coil-kt.coil3", name = "coil-compose", version.ref = "coil" }
coil-ktor = { module = "io.coil-kt.coil3:coil-network-ktor3", version.ref = "coil" }

androidx-compose-paging = { group = "androidx.paging", name = "paging-compose", version.ref = "paging" }
androidx-paging-runtime = { group = "androidx.paging", name = "paging-runtime-ktx", version.ref = "paging" }
androidx-paging-testing = { group = "androidx.paging", name = "paging-testing", version.ref = "paging" }

kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "serialization" }
kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "datetime" }
kotlinx-collections-immutable = { group = "org.jetbrains.kotlinx", name = "kotlinx-collections-immutable", version.ref = "immutableCollection" }

accompanist-placeholder = { module = "com.google.accompanist:accompanist-placeholder", version.ref = "accompanist" }
accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }

kermit = { group = "co.touchlab", name = "kermit", version.ref = "kermit" }

junit-bom = { group = "org.junit", name = "junit-bom", version.ref = "junit" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter" }
junit-launcher = { group = "org.junit.platform", name = "junit-platform-launcher" }
mockk-android = { group = "io.mockk", name = "mockk-android", version.ref = "mockk" }
mockk-agent = { group = "io.mockk", name = "mockk-agent", version.ref = "mockk" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidxJunit" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso" }
androidx-test-runner = { group = "androidx.test", name = "runner", version.ref = "androidxTest" }
robolectric = { group = "org.robolectric", name = "robolectric", version.ref = "robolectric" }
androidx-test = { group = "androidx.test", name = "core-ktx", version.ref = "androidxTest" }

androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
androidx-room-paging = { group = "androidx.room", name = "room-paging", version.ref = "room" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
androidx-room-testing = { group = "androidx.room", name = "room-testing", version.ref = "room" }

androidx-datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore" }
androidx-datastore-core = { group = "androidx.datastore", name = "datastore-core", version.ref = "datastore" }

hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }
hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hiltCompose" }
hilt-gradlePlugin = { group = "com.google.dagger", name = "hilt-android-gradle-plugin", version.ref = "hilt" }
hilt-test = { group = "com.google.dagger", name = "hilt-android-testing", version.ref = "hilt" }

coroutine-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutineTest" }

google-gms = { module = "com.google.gms:google-services", version.ref = "gms" }
google-firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "fbBom" }
google-firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics" }
google-firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics" }

androidx-junit-ktx = { group = "androidx.test.ext", name = "junit-ktx", version.ref = "junitKtx" }

detekt-gradle = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt" }
detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }
detekt-rules-compose = { module = "io.nlopez.compose.rules:detekt", version.ref = "detektCompose" }
detekt-api = { module = "io.gitlab.arturbosch.detekt:detekt-api", version.ref = "detekt" }
detekt-test = { module = "io.gitlab.arturbosch.detekt:detekt-test", version.ref = "detekt" }

[plugins]
kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
room = { id = "androidx.room", version.ref = "room" }
vkompose = { id = "com.vk.vkompose", version.ref = "vkompose" }
robolectric-junit5 = { id = "tech.apter.junit5.jupiter.robolectric-extension-gradle-plugin", version.ref = "robolectricExt" }
gms = { id = "com.google.gms.google-services", version.ref = "gms" }
firebaseCrashlytics = { id = "com.google.firebase.crashlytics", version.ref = "fbCrashlytics" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }

convention-application-common = { id = "workeeper.android.application.common", version = "1.0" }
convention-application-store = { id = "workeeper.android.application.store", version = "1.0" }
convention-application-dev = { id = "workeeper.android.application.dev", version = "1.0" }

convention-androidLibrary = { id = "workeeper.android.androidLibrary", version = "1.0" }
convention-composeLibrary = { id = "workeeper.android.composeLibrary", version = "1.0" }
convention-roomLibrary = { id = "workeeper.room.library", version = "1.0" }
convention-lint = { id = "workeeper.lint.convention", version = "1.0" }

[bundles]
lifecycle = [
    "lifecycle-compose",
    "lifecycle-viewModel"
]

accompanist = [
    "accompanist-placeholder",
    "accompanist-systemuicontroller",
]

compose = [
    "androidx-compose-activity",
    "androidx-compose-material3",
    "androidx-compose-ui",
    "androidx-compose-material-icons-core",
    "androidx-compose-material-icons-extended",
    "androidx-compose-tooling-preview",
    "androidx-compose-foundation",
    "androidx-compose-paging",
    "androidx-compose-animation",
    "androidx-compose-animationGraphics",
    "androidx-compose-runtime",
    "coil-compose"
]

android-test = [
    "androidx-junit",
    "androidx-espresso-core",
    "androidx-test-runner",
    "hilt-test"
]

test = [
    "mockk-android",
    "mockk-agent",
    "junit-jupiter",
    "robolectric",
    "androidx-test",
    "coroutine-test",
]

room = [
    "androidx-room-runtime",
    "androidx-room-paging",
    "androidx-room-ktx"
]